### PR TITLE
Added Github icon next to "Report a bug" button

### LINKED ISSUE #250: Put a github icon somewhere on the page, maybe next to report a bug

### PR DESCRIPTION
**Pull request by ketansahugit**
## Pull Request Summary

This pull request addresses issue #250 

### Changes Made

- Added Github Icon next to the "Report a Bug" button

Closes #250

### CODE REVIEW

**Comment by ketansahugit** [comment]
@K20shores  What do you think about the changes i made?

File: src/components/Layout.jsx [hunk 1]
```diff
@@ -203,13 +203,24 @@ function Layout(props) {
...
                     href="https://github.com/NCAR/music-box-interactive-client/issues/new?template=bug_report.md"
                   >
                     <h5>Report a bug</h5>
                   </a>
+                  <a
+                    className="footer-link"
+                    href="https://github.com/NCAR/music-box-interactive-client"
+                  >
+                    <img
+                      src="https://assets.dryicons.com/uploads/icon/svg/8312/cc33248a-e56e-4e7f-93f4-0e16350e5768.svg"
```
Comment (K20shores) [inline src/components/Layout.jsx:219]: @ketansahugit I like the placement! Instead of that URL, I'd prefer an option that can be used at build time. Could you look into using an icon from [material UI](https://mui.com/material-ui/material-icons/)?

**Review by K20shores — CHANGES_REQUESTED** [review]

File: src/components/Layout.jsx (hunk 1 above)
Comment (ketansahugit) [reply src/components/Layout.jsx]: @K20shores  Hi, I have replaced the URL with material UI Icon.

Comment (K20shores) [reply src/components/Layout.jsx]: Beautiful. Thanks!

**Review by K20shores — APPROVED** [review]
